/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package org.cap

import spock.lang.Specification

class MainTest extends Specification {
    def "application has a greeting"() {
    }
}
